import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { network } from "hardhat";

describe("Potluck", async function () {
    async function deployPotluckFixture() {
        const { viem } = await network.connect();
        const publicClient = await viem.getPublicClient();
        const [owner, user1, user2] = await viem.getWalletClients();

        // Deploy Mock USDC
        const mockUSDC = await viem.deployContract("ERC20Mock", ["Mock USDC", "mUSDC", owner.account.address, 1000000n * 10n ** 6n]);

        // Deploy Tickets
        const tickets = await viem.deployContract("PotluckTickets");

        // Deploy PrizePool
        const prizePool = await viem.deployContract("PrizePool", [tickets.address, mockUSDC.address]);

        // Deploy Vault
        const vault = await viem.deployContract("PotluckVault", [mockUSDC.address, tickets.address, prizePool.address]);

        // Setup relationships
        await tickets.write.setVault([vault.address]);

        // Give users some USDC
        const depositAmount = 100n * 10n ** 6n;
        await mockUSDC.write.mint([user1.account.address, depositAmount]);
        await mockUSDC.write.mint([user2.account.address, depositAmount]);

        return { vault, tickets, prizePool, mockUSDC, owner, user1, user2, depositAmount, publicClient };
    }

    describe("Deployment", function () {
        it("Should set the right tickets per asset", async function () {
            const { vault } = await deployPotluckFixture();
            assert.equal(await vault.read.ticketsPerAsset(), 1n);
        });
    });

    describe("Deposits and Tickets", function () {
        it("Should accept deposits and mint tickets 1:1", async function () {
            const { vault, tickets, mockUSDC, user1, depositAmount } = await deployPotluckFixture();

            // Approve vault
            await mockUSDC.write.approve([vault.address, depositAmount], { account: user1.account });

            // Deposit
            await vault.write.deposit([depositAmount, user1.account.address], { account: user1.account });

            // Check vault balance
            assert.equal(await mockUSDC.read.balanceOf([vault.address]), depositAmount);

            // Check user shares (pUSDC)
            assert.equal(await vault.read.balanceOf([user1.account.address]), depositAmount);

            // Check user tickets
            assert.equal(await tickets.read.balanceOf([user1.account.address]), depositAmount);
        });
    });

    describe("Yield and Prize Pool", function () {
        it("Should sweep excess yield to the prize pool", async function () {
            const { vault, tickets, prizePool, mockUSDC, user1, depositAmount, owner } = await deployPotluckFixture();

            // User deposits $100
            await mockUSDC.write.approve([vault.address, depositAmount], { account: user1.account });
            await vault.write.deposit([depositAmount, user1.account.address], { account: user1.account });

            // Simulate $10 of yield generated by an external protocol (e.g. Aave)
            const yieldAmount = 10n * 10n ** 6n;
            await mockUSDC.write.approve([vault.address, yieldAmount], { account: owner.account });
            await vault.write.injectYield([yieldAmount], { account: owner.account });

            // Vault holds 110 total, but user shares are only 100
            assert.equal(await mockUSDC.read.balanceOf([vault.address]), depositAmount + yieldAmount);

            // Sweep the yield
            await vault.write.sweepYield();

            // Vault should have 100 again
            assert.equal(await mockUSDC.read.balanceOf([vault.address]), depositAmount);

            // Prize Pool should have the 10 yield
            assert.equal(await mockUSDC.read.balanceOf([prizePool.address]), yieldAmount);
        });
    });
});
